### ISSUE TITLE
Allow uninitialized let

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/ElementaryJS#120]
Can we allow uninitialized let as long as it is used before definition?

**Comment by joydeep-b** [comment]
The goal of this restriction was to eliminate yet another common source of undefined.
Is it possible to statically / dynamically check for assignment before read?
Else, undefined will abound.

**Comment by arjunguha** [comment]
Yes, it possible to do what you said. I suggest @sp1tz take a crack at this. It's a nice little program analysis problem.
