### ISSUE TITLE
Disallow bitwise operators

### ISSUE THREAD

**Issue by sp1tz** [plasma-umass/ElementaryJS#142]
Justification:
- No integers in JS.
- They are very slow here, being far from hardware.
- Typos; for example `bool1 & bool2` instead of `bool1 && bool2`.
- An indicator of overly clever code, which decreases maintainability.

[Update linter too.]( https://github.com/plasma-umass/ElementaryJS/blob/master/tslint.json#L7)

**Comment by arjunguha** [comment]
No reason to disallow bitwise operators. They are useful, I actually use them in class, and we are here to teach students computer science, including the hard parts.
