### ISSUE TITLE
Use of undefined primative

### ISSUE THREAD

**Issue by sp1tz** [plasma-umass/ElementaryJS#176]
Should we disallow explicit assignment of `undefined`? Generally bad practice to do so as it is an internal value. In contrast, `null` is for external use by the programmer.
```js
let a = undefined, //discouraged
    b = null; //encouraged
```
This would require buy-in from EJS stakeholders.

**Comment by arjunguha** [comment]
I don't agree with this change. Personally, I use `a= undefined` and never use `a = null`. TypeScript encourages this pattern.
