### ISSUE TITLE
Support for sudo

### ISSUE THREAD

**Issue by sp1tz** [plasma-umass/ElementaryJS#183]
Previously: https://github.com/umass-compsci220/Ocelot/issues/22
Branch: https://github.com/plasma-umass/ElementaryJS/tree/sudo

**Comment by arjunguha** [comment]
Not sure why this is assigned to me. I don't think this feature is really needed. When designing 220, we thought we would periodically present how "real JavaScript" works. But, that turns out to be unnecessary and undesirable.

**Comment by sp1tz** [comment]
I had a hunch this wasn't on the roadmap anymore given it's been stagnant for such a long time. Nonetheless when I transferred it from Ocelot, it had you assigned there so I kept it consistent.
