### ISSUE TITLE
Allow switch with mandatory break

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/ElementaryJS#46]
Instead of completely disabling switch, what if we require breaks at the end of each case instead? This is what Java does.

**Comment by arjunguha** [comment]
@joydeep-b

**Comment by joydeep-b** [comment]
Sure, sounds good.

**Comment by arjunguha** [comment]
This could be okay:

```
switch (e) {
  case 1:
  case 2:
     f()
    break
}
```

However this is bad:

```
switch (e) {
  case 1:
    g()
  case 2:
     f()
    break
}
```

**Comment by arjunguha** [comment]
Can also terminate with returns instead of break!

**Comment by joydeep-b** [comment]
I disagree. Terminate with returns, multiple case clauses, etc. are all fancy program features that advanced programmers feel superior using, and that intro programmers accidentally trigger and cannot debug.

The mandatory break after every clause may be a compromise, but if you want to allow these other things, might as well hand them the full noose and allow them to do switch cases without any restriction.

**Comment by joydeep-b** [comment]
> This could be okay:
> 
> ```
> switch (e) {
>   case 1:
>   case 2:
>      f()
>     break
> }
> ```
> However this is bad:
> 
> ```
> switch (e) {
>   case 1:
>     g()
>   case 2:
>      f()
>     break
> }
> ```

Why is the second one bad if the first is okay? If you understand why the first works, you should also understand what the second one does.

**Comment by arjunguha** [comment]
OK, so no fallthrough at all? That is what Java/C# do, right?

**Comment by joydeep-b** [comment]
Needs more specs. Which of the following cases are acceptable?

```js
switch (i) {
  case 0: {
    console.log(0);
    break;
  }
  case 1: {
    console.log(1);
  }
  break;
  case 2: 
    console.log(2);
    break;
}
```

I propose case 2 be disallowed (for the same reason that if blocks must be followed by braced blocks), but case 0 and 1 are okay.

**Comment by sp1tz** [comment]
Sure, that would be consistent.

In regards to `default`, it seems that it should not be required but can be used. If it's present, require a block but not a `break`. Is that correct?

**Comment by joydeep-b** [comment]
If `default` does not have a `break`, then it must be the last block. Else, bad things will happen, for example:

```js
let i = 2;

switch(i) {
  case 0: {
    console.log(0);
    break;
  }
  default: {
    console.log("???");
  }
  case 1: {
    console.log(1);
    break;
  }
}
```

**Comment by sp1tz** [comment]
@joydeep-b & @arjunguha: I'm getting conflicting messages from the two of you on what should be permitted/required within a switch statement. Could the two of you hash things out and relay the information clearly/concisely to me? Or I can try to be present when you meet.

If things are sorted out by EOD tomorrow, then I think we can get this in with the require changes in the next version of EJS.

**Comment by joydeep-b** [comment]
We had a discussion earlier today which might change this entirely. Let's place a hold on this until we decide the forward direction of language restrictions in EJS for the class.

**Comment by sp1tz** [comment]
https://github.com/plasma-umass/ElementaryJS/pull/123
