### ISSUE TITLE
New file errors do not get cleared

### ISSUE THREAD

**Issue by joydeep-b** [plasma-umass/ElementaryJS#50]
Steps to reproduce:
1. Click on "New"
2. Enter an invalid name, e.g. "BAD"
3. Abort the new file creation, by clicking on the delete icon.
4. Click on "New" to start over.

Error behavior: At step 4, the new file entry shows the last error message.
Expected behavior: At step 4, the new file entry should not have an error message.

**Comment by arjunguha** [comment]
Report this under Ocelot?

**Comment by joydeep-b** [comment]
Oops, yes. So many repos!
